### ISSUE TITLE
Can be work on api 17 ?? the min api set 18 ....

### ISSUE THREAD

**Issue by mahmooddagga** [UrbanChrisy/Exposure-Video-Player#1]
Can be work on API 17 ?? the min API set 18 ....

**Comment by UrbanChrisy** [comment]
Yes it could work. But it won't be able to until the next update, yet that won't be for awhile due to other priorities at the moment. Just have to be patient. You could fork the repo and change the api version in the gradle file, my only solution at the moment.

**Comment by mahmooddagga** [comment]
thanks  
I hope it will be soon

**Comment by UrbanChrisy** [comment]
Ill see if I have time tonight for you. It'll be a new update.
