### ISSUE TITLE
Error:Failed to resolve: com.android.support.constraint:constraint-layout:1.0.0-alpha8 

### ISSUE THREAD

**Issue by moizest89** [UrbanChrisy/Exposure-Video-Player#3]
I try to compile when to finish every say: **Error:Failed to resolve: com.android.support.constraint:constraint-layout:1.0.0-alpha8 **

Background: I'm using Android Strudio 1.5.1 and now it's impossible for me update.

Regards.

**Comment by UrbanChrisy** [comment]
So from what I have knowledge on, its nothing todo with my library.  First of all update android studio to the latest version which is roughly around 2. Then do the same for gradle if not already and then the same again for your build tools which is 25.0.0. Then lastly invalidate caches and restart.

If it continues then ill have a look, at switching out the layout for a relative next week.

**Comment by UrbanChrisy** [comment]
Also another issue is I do not use constraint layout anywhere in my library. I have thought about it which is weird tbh. Any way check your code. If you want I can have a look also.

**Comment by UrbanChrisy** [comment]
New version on jcenter. v1.0.5. Should work fine.
